### ISSUE TITLE
Rounds differently from `fmt` at same precision

### ISSUE THREAD

**Issue by radix** [dtolnay/dtoa#11]
I'm honestly clueless about the considerations involved here, but when I wrote some super naive unit tests for some json serialization code that dealt with floating points, I noticed that some numbers would format differently when passed to `std::fmt` vs `dtoa`.

Here's a reproduction example:

```rust
extern crate serde_json;
extern crate dtoa;

fn main() {
    let num: f64 = 10.509352098150472;
    let fmt = format!("{}", num);
    let mut dtoa_v = Vec::new();
    dtoa::write(&mut dtoa_v, num).unwrap();
    let dtoa_s = String::from_utf8(dtoa_v).unwrap();
    let json = serde_json::to_string(&num).unwrap();
    println!(" fmt: {}\njson: {}\ndtoa: {}", fmt, json, dtoa_s);
}
```

Output:

```
 fmt: 10.509352098150472
json: 10.509352098150473
dtoa: 10.509352098150473
```

Is this expected?

**Comment by dtolnay** [comment]
The only guarantee is that when you parse it, you get the original number back (assuming your parser is correct). There is no guarantee about rounding or number of digits.

```rust
fn main() {
    println!("{}", "10.509352098150472".parse::<f64>().unwrap());
    println!("{}", "10.509352098150473".parse::<f64>().unwrap());
}
```

**Comment by radix** [comment]
Alrighty, just wanted to make sure. Thanks @dtolnay!
