### ISSUE TITLE
Replace mem::uninitialized with MaybeUninit

### ISSUE THREAD

**Issue by lopopolo** [dtolnay/dtoa#17]
`dtoa` contains a call to `mem::uninitialized`. I think `MaybeUninit` is the right way to get an uninitialized slice now.

Is it possible to bump the MSRV or use the `rustversion` macro to use the new std API?

I can send a PR if you’re interested in this change.

**Comment by dtolnay** [comment]
Thanks! I published 0.4.5 which fixes the warnings.
