### ISSUE TITLE
[feature request] dtoa::fmt that takes a fmt::Write

### ISSUE THREAD

**Issue by lopopolo** [dtolnay/dtoa#18]
Since the stringified representation of a float is all ASCII, would it be possible to add `dtoa::fmt` function that takes a `fmt::Write` as the destination? This would mirror the API in `itoa`.

**Comment by dtolnay** [comment]
The most recent version of this crate returns the formatted number as &amp;str, which you can write into a `fmt::Write` using https://doc.rust-lang.org/core/fmt/trait.Write.html#tymethod.write_str if needed.
