### ISSUE TITLE
Number failing to write to buffer

### ISSUE THREAD

**Issue by kurtlawrence** [dtolnay/dtoa#22]
Hi there,

Running the following code:
```rust
let mut buf = [0; 20];
dtoa::write(&mut buf[..], 0.00316114_f64).expect("not to crash");
println!("{:?}", buf);
```

results in a panic.

This was run on rust `nightly-2020-07-26-x86_64-unknown-linux-gnu`, tested on `stable-x86_64-unknown-linux-gnu` and crashes, along with `nightly-2020-07-26-x86_64-pc-windows-msvc`.

Crashes in `release` builds as well.

**Comment by dtolnay** [comment]
Does it work with a bigger buffer?

**Comment by kurtlawrence** [comment]
Yes it does, with a buffer size of 21 bytes. Sorry I should have checked that.

**Comment by dtolnay** [comment]
Sounds good!

I'm not sure why it would format in such a long representation, but this code is just a direct port from [dtoa.h](https://github.com/Tencent/rapidjson/blob/master/include/rapidjson/internal/dtoa.h) so you'd need to follow up there about it; we end up pulling in whatever fix they make upstream.

```cpp
#include "rapidjson/document.h"
#include "rapidjson/writer.h"
#include <iostream>

int main() {
  rapidjson::StringBuffer sb;
  rapidjson::Writer<rapidjson::StringBuffer> writer(sb);
  auto result = rapidjson::Value(0.00316114).Accept(writer);
  assert(result);
  std::cout << sb.GetLength() << std::endl;
}
```

```
21
```

**Comment by kurtlawrence** [comment]
All good, I incorrectly assumed that 20 bytes would cover all representations.
Thanks for the fast response!

I am not sure what minimum buffer size would be required to cover all float cases, I just tested with `2f64.pow(67)` and it required a 23-byte buffer. I took 2^67 from a reference to it in the white paper. I suspect the 2 extra bytes come from the `.0` at the end.
