### ISSUE TITLE
Minus sign missing on negative numbers

### ISSUE THREAD

**Issue by zotta** [dtolnay/dtoa#26]
You library currently has a major bug: Negative numbers are printed without the minus sign.

Debugging the issue revealed that The minus sign is written to the buffer, but not included in the output slice.

Please make sure that the returned string slice actually contains the sign.

Offending code:
```rust
let mut buf_ptr = buf.bytes.as_mut_ptr() as *mut u8;
if value < 0.0 {
    *buf_ptr = b'-';
    buf_ptr = buf_ptr.offset(1);
    value = -value;
}
let (length, k) = grisu2(value, buf_ptr);
let end = dtoa::prettify(buf_ptr, length, k);
let len = end as usize - buf_ptr as usize;
str::from_utf8_unchecked(slice::from_raw_parts(buf_ptr, len))
```
Propsed fix:
```rust
let start = buf.bytes.as_mut_ptr() as *mut u8;
let len = end as usize - start as usize;
str::from_utf8_unchecked(slice::from_raw_parts(start, len))
```

**Comment by dtolnay** [comment]
Thanks, fixed in 1.0.2.

FWIW I don't know of any reason to use this crate &mdash; https://github.com/dtolnay/ryu should be better in all ways and is what serde_json uses for floats.
