### ISSUE TITLE
Support no_std

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/dtoa#8]

**Comment by pierre-rouanet** [comment]
Hi, great work!

Any update on this or roadmap? 
I'm currently trying to use serde_json on a microcontroller and this seems to be one of the missing step.

I'm new to Rust but let me know if I can help!

**Comment by dtolnay** [comment]
No-std support for serde_json has not been on my roadmap because nobody has needed it so far, but if you need it then it's time to start implementing it. I filed https://github.com/serde-rs/json/issues/362 to follow up. Would you be interested in contributing a PR for that?

I believe no-std serde_json can be done without no-std dtoa by using `write!(..., "{}", f)` for floats.

**Comment by pierre-rouanet** [comment]
Great I'll try to have a look into this as soon as I have a bit of free time!

**Comment by perlindgren** [comment]
I'm interested too.

**Comment by MrBuddyCasino** [comment]
no_std would be great! There is numtoa for ints, but nothing for floats.
